name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs_on: ubuntu-latest
        steps:
            - name: Checkout repo
              actions: actions/checkout@v4
            
            - name: Install cowsay program
              run: sudo apt-get install cowsay -y

            - name: Execute the cowsay command
              run: cowsay -f dragon "I'm Smaug and I was voiced by Benedict Cumberbatch, none other than Sherlock Strange himself" >> dragon.txt

            - name: Test if the file exists
              run: grep -i "dragon" dragon.txt

            - name: Read the file
              run: cat dragon.txt

            - name: List the files
              run: ls -lrta